GOOGLE_SHEETS_MAPPING = {
    "timestamp": "Дата и время ответа",
    "username": "Имя пользователя (Telegram)",
    "user_id": "Telegram ID",
    "gender": "Пол",
    "age": "Возраст",
    "first_time": "Ранее бывал в нашем ресторане",
    "visit_source": "Как узнал о ресторане",
    "visit_frequency": "Частота посещения ресторанов",
    "last_visit_satisfaction": "Удовлетворён последним визитом к нам",
    "last_visit_issues": "Были ли трудности при визите",
    "issues_description": "Описание трудностей",
    "cuisine_preference": "Любимая кухня",
    "menu_satisfaction": "Устраивает меню",
    "menu_wishes": "Пожелания по меню",
    "avg_bill": "Комфортный средний чек",
    "reservation_preference": "Способ бронирования",
    "important_factors": "Важные факторы при выборе ресторана",
    "delivery_interest": "Пользуется доставкой",
    "loyalty_program": "Важность программы лояльности",
    "recommendation_willingness": "Готов рекомендовать ресторан",
    "improvement_needed": "Требуются ли улучшения",
    "improvement_suggestions": "Предложения по улучшению"
}

COLUMN_ORDER = [
    "timestamp",
    "username",
    "user_id",
    "gender",
    "age",
    "first_time",
    "visit_source",
    "visit_frequency",
    "last_visit_satisfaction",
    "last_visit_issues",
    "issues_description",
    "cuisine_preference",
    "menu_satisfaction",
    "menu_wishes",
    "avg_bill",
    "reservation_preference",
    "important_factors",
    "delivery_interest",
    "loyalty_program",
    "recommendation_willingness",
    "improvement_needed",
    "improvement_suggestions"
]
